import { useRef, useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowLeft, Upload, FileSpreadsheet, FileJson, FileText, Download, CircleCheck as CheckCircle2, TriangleAlert as AlertTriangle, FolderOpen } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useTeacherStore } from '../store';
import * as svc from '../services';
import { parseCSV, parseExcel, parseJSON, validateImportRows, downloadQuestionImportTemplateCSV, downloadQuestionImportTemplateExcel, downloadQuestionImportTemplateJSON, type ImportPreview, type ValidatedImportRow } from '../importExport';
import { cn } from '@/utils/cn';

type ImportFormat='csv'|'xlsx'|'json';
const OPTION_LETTERS=['A','B','C','D'] as const;

export function QuestionImportPage(){
 const navigate=useNavigate(); const [params]=useSearchParams(); const presetSetId=params.get('setId');
 const {categories,loadQuestions,loadCategories,loadQuestionSets}=useTeacherStore(); const fileRef=useRef<HTMLInputElement>(null); const importingRef=useRef(false);
 const [format,setFormat]=useState<ImportFormat>('csv'); const [fileName,setFileName]=useState<string|null>(null); const [preview,setPreview]=useState<ImportPreview|null>(null); const [parseError,setParseError]=useState<string|null>(null); const [importing,setImporting]=useState(false); const [setName,setSetName]=useState(''); const [existingSet,setExistingSet]=useState<{id:string;name:string}|null>(null); const [importResult,setImportResult]=useState<{imported:number;failed:{row:ValidatedImportRow;reason:string}[];setName:string;setId:string}|null>(null);
 useEffect(()=>{if(presetSetId)svc.fetchQuestionSet(presetSetId).then(s=>{if(s){setExistingSet({id:s.id,name:s.name});setSetName(s.name)}}).catch(e=>setParseError(e instanceof Error?e.message:'Failed to load Question Set'))},[presetSetId]);
 const resetFile=()=>{setFileName(null);setPreview(null);setParseError(null);setImportResult(null);if(fileRef.current)fileRef.current.value=''};
 const downloadTemplate=()=>format==='csv'?downloadQuestionImportTemplateCSV():format==='xlsx'?downloadQuestionImportTemplateExcel():downloadQuestionImportTemplateJSON();
 const handleFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setParseError(null);setImportResult(null);setFileName(file.name);try{const parsed=format==='csv'?parseCSV(await file.text()):format==='xlsx'?parseExcel(await file.arrayBuffer()):parseJSON(await file.text());if(!parsed.length){setPreview(null);setParseError('No usable rows were found in this file.');return}setPreview(validateImportRows(parsed))}catch(err){setPreview(null);setParseError(err instanceof Error?err.message:'Failed to parse file')}};
 const handleImport=async()=>{if(!preview||preview.valid.length===0||importingRef.current)return;if(!existingSet&&!setName.trim()){setParseError('Question Set name is required.');return}importingRef.current=true;setImporting(true);try{
   const target=existingSet??await svc.createQuestionSet(setName.trim());
   const categoryCache=new Map<string,string|null>(); categories.forEach(c=>categoryCache.set(c.name.trim().toLowerCase(),c.id));
   const resolveCategory=async(name:string)=>{const key=name.trim().toLowerCase();if(!key)return null;if(categoryCache.has(key))return categoryCache.get(key)!;const c=await svc.createCategory(name.trim());categoryCache.set(key,c.id);return c.id};
   let imported=0;const failed:{row:ValidatedImportRow;reason:string}[]=[];
   for(const item of preview.valid){const {row}=item;const options=[row.optionA,row.optionB,row.optionC,row.optionD].map((label,idx)=>({label,isCorrect:OPTION_LETTERS[idx]===row.correctAnswer,sortOrder:idx})).filter(o=>o.label.trim());try{const categoryId=await resolveCategory(row.category);await svc.createQuestion({questionSetId:target.id,categoryId,type:'multiple_choice',question:row.question,difficulty:row.difficulty as 'easy'|'medium'|'hard',points:10,explanation:row.explanation||null,options});imported++}catch(err){failed.push({row:item,reason:err instanceof Error?err.message:'Failed to save'})}}
   await Promise.all([loadQuestions(),loadCategories(),loadQuestionSets()]);setImportResult({imported,failed,setName:target.name,setId:target.id});
 }finally{importingRef.current=false;setImporting(false)}};
 const formatOptions=[{value:'csv' as ImportFormat,label:'CSV',icon:FileText},{value:'xlsx' as ImportFormat,label:'Excel',icon:FileSpreadsheet},{value:'json' as ImportFormat,label:'JSON',icon:FileJson}];
 return <div className="mx-auto max-w-4xl space-y-4"><div className="flex items-center gap-3"><button onClick={()=>navigate(existingSet?`/teacher/questions/sets/${existingSet.id}`:'/teacher/questions')} className="flex h-9 w-9 items-center justify-center rounded-xl text-muted-foreground hover:bg-muted/40"><ArrowLeft size={20}/></button><div><h1 className="font-display text-xl font-semibold">Import Question Set</h1><p className="text-xs text-muted-foreground">Import File → Question Set → Questions</p></div></div>
 <AnimatePresence mode="wait">{importResult?<motion.div key="done" initial={{opacity:0}} animate={{opacity:1}}><Card><CardContent className="flex flex-col items-center gap-3 p-8 text-center"><div className={cn('flex h-14 w-14 items-center justify-center rounded-2xl',importResult.failed.length?'bg-amber-500/15 text-amber-600':'bg-emerald-500/15 text-emerald-600')}><CheckCircle2 size={28}/></div><h2 className="font-display text-lg font-semibold">Import Complete</h2><p className="text-sm text-muted-foreground">{importResult.imported} question{importResult.imported===1?'':'s'} added to <strong>{importResult.setName}</strong>.</p>{importResult.failed.length>0&&<div className="w-full rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-left text-xs"><p className="mb-1 font-medium text-amber-600">{importResult.failed.length} row(s) failed:</p><ul className="space-y-0.5 text-muted-foreground">{importResult.failed.map((f,i)=><li key={i}>Row {f.row.rowNumber}: {f.reason}</li>)}</ul></div>}<div className="flex gap-2"><Button variant="outline" onClick={resetFile}>Import Another File</Button><Button onClick={()=>navigate(`/teacher/questions/sets/${importResult.setId}`)}>Open Question Set</Button></div></CardContent></Card></motion.div>:<motion.div key="form" initial={{opacity:0}} animate={{opacity:1}} className="space-y-4">
   <Card><CardContent className="p-5"><label className="mb-2 block text-xs font-medium text-muted-foreground">1. Question Set</label>{existingSet?<div className="flex items-center gap-3 rounded-2xl border border-primary/30 bg-primary/5 p-4"><FolderOpen size={22} className="text-primary"/><div><p className="text-sm font-semibold">{existingSet.name}</p><p className="text-xs text-muted-foreground">New imported questions will be added to this set.</p></div></div>:<><input value={setName} onChange={e=>setSetName(e.target.value)} className="w-full rounded-2xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary dark:border-border-dark dark:bg-surface-dark" placeholder="Example: Ulangan Harian TKJ 4"/><p className="mt-2 text-xs text-muted-foreground">All questions in this file will become one Question Set.</p></>}</CardContent></Card>
   <Card><CardContent className="p-5"><label className="mb-2 block text-xs font-medium text-muted-foreground">2. Choose a file format</label><div className="grid grid-cols-3 gap-3">{formatOptions.map(opt=><button key={opt.value} onClick={()=>{setFormat(opt.value);resetFile()}} className={cn('flex flex-col items-center gap-2 rounded-2xl border p-4',format===opt.value?'border-primary bg-primary/10 text-primary':'border-border text-muted-foreground dark:border-border-dark')}><opt.icon size={24}/><span className="text-sm font-medium">{opt.label}</span></button>)}</div></CardContent></Card>
   <Card><CardContent className="flex items-center justify-between gap-3 p-5"><div><p className="text-sm font-medium">3. Download the template</p><p className="text-xs text-muted-foreground">Question, Option A–D, Correct Answer, Explanation, Difficulty, Category.</p></div><Button variant="outline" onClick={downloadTemplate}><Download size={16}/> Template</Button></CardContent></Card>
   <Card><CardContent className="p-5"><label className="mb-2 block text-xs font-medium text-muted-foreground">4. Upload your file</label><button onClick={()=>fileRef.current?.click()} className="flex w-full flex-col items-center gap-3 rounded-2xl border-2 border-dashed border-border py-8 hover:border-primary dark:border-border-dark"><Upload size={32} className="text-muted-foreground"/><span className="text-sm font-medium">{fileName??`Click to upload a ${format.toUpperCase()} file`}</span></button><input ref={fileRef} type="file" accept={format==='csv'?'.csv':format==='xlsx'?'.xlsx,.xls':'.json'} className="hidden" onChange={handleFile}/>{parseError&&<p className="mt-3 flex items-center gap-2 rounded-xl bg-red-500/10 px-3 py-2 text-xs text-red-500"><AlertTriangle size={14}/>{parseError}</p>}</CardContent></Card>
   {preview&&<Card><CardContent className="p-0"><div className="flex flex-wrap items-center justify-between px-5 py-4"><h2 className="text-sm font-semibold">5. Preview & Validate</h2><div className="flex gap-3 text-xs"><span>{preview.totalRows} total</span><span className="text-emerald-600">{preview.valid.length} valid</span>{preview.invalid.length>0&&<span className="text-red-500">{preview.invalid.length} invalid</span>}</div></div><div className="border-t border-border dark:border-border-dark"/><div className="max-h-96 overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-muted/30"><tr><th className="px-3 py-2 text-left">#</th><th className="px-3 py-2 text-left">Question</th><th className="px-3 py-2 text-left">Correct</th><th className="px-3 py-2 text-left">Difficulty</th><th className="px-3 py-2 text-left">Status</th></tr></thead><tbody className="divide-y divide-border dark:divide-border-dark">{preview.all.map(item=><tr key={item.rowNumber} className={!item.valid?'bg-red-500/5':undefined}><td className="px-3 py-2">{item.rowNumber}</td><td className="max-w-[420px] truncate px-3 py-2">{item.row.question||'(empty)'}</td><td className="px-3 py-2">{item.row.correctAnswer||'—'}</td><td className="px-3 py-2 capitalize">{item.row.difficulty}</td><td className="px-3 py-2">{item.valid?<span className="text-emerald-600">Valid</span>:<span className="text-red-500">{item.reasons[0]}</span>}</td></tr>)}</tbody></table></div></CardContent></Card>}
   {preview&&<Button onClick={handleImport} disabled={importing||preview.valid.length===0||(!existingSet&&!setName.trim())} className="w-full">{importing?'Importing...':`Import ${preview.valid.length} Question${preview.valid.length===1?'':'s'} into ${existingSet?.name??(setName.trim()||'Question Set')}`}</Button>}
 </motion.div>}</AnimatePresence></div>;
}
