import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Upload, Plus, ClipboardList, Trash2, Archive, RotateCcw, Eye, Copy } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { useTeacherStore } from '../store';
import * as svc from '../services';
import { QUESTION_TYPE_LABELS, DIFFICULTY_LABELS, type Question, type QuestionSet } from '../types';

export function QuestionSetPage(){
  const navigate=useNavigate(); const {id}=useParams<{id:string}>();
  const {deleteQuestion,duplicateQuestion,archiveQuestion}=useTeacherStore();
  const [set,setSet]=useState<QuestionSet|null>(null); const [questions,setQuestions]=useState<Question[]>([]); const [loading,setLoading]=useState(true); const [confirmDelete,setConfirmDelete]=useState<string|null>(null);
  const load=async()=>{if(!id)return;setLoading(true);try{const [qs,active,archived]=await Promise.all([svc.fetchQuestionSet(id),svc.fetchQuestionsBySetId(id,false),svc.fetchQuestionsBySetId(id,true)]);setSet(qs);setQuestions([...active,...archived]);}finally{setLoading(false)}};
  useEffect(()=>{load()},[id]);
  if(loading)return <div className="py-12 text-center text-sm text-muted-foreground">Loading Question Set...</div>;
  if(!set)return <div className="mx-auto max-w-4xl py-12 text-center"><p className="text-sm text-muted-foreground">Question Set not found.</p><button onClick={()=>navigate('/teacher/questions')} className="mt-3 rounded-2xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Back to Question Bank</button></div>;
  return <div className="mx-auto max-w-4xl space-y-4">
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={()=>navigate('/teacher/questions')} className="flex h-9 w-9 items-center justify-center rounded-xl text-muted-foreground hover:bg-muted/40"><ArrowLeft size={20}/></button><div><h1 className="font-display text-2xl font-semibold">{set.name}</h1><p className="mt-0.5 text-sm text-muted-foreground">{questions.length} questions · Created {new Date(set.createdAt).toLocaleDateString()}</p></div></div><div className="flex gap-2"><button onClick={()=>navigate(`/teacher/questions/import?setId=${set.id}`)} className="flex items-center gap-2 rounded-2xl border border-border px-3 py-2 text-sm font-medium dark:border-border-dark"><Upload size={16}/> Import</button><button onClick={()=>navigate(`/teacher/questions/new?setId=${set.id}`)} className="flex items-center gap-2 rounded-2xl border border-border px-3 py-2 text-sm font-medium dark:border-border-dark"><Plus size={16}/> Add Question</button><button onClick={()=>navigate(`/teacher/exams/new?questionSetId=${set.id}`)} className="flex items-center gap-2 rounded-2xl bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><ClipboardList size={16}/> Create Exam</button></div></div>
    <Card><CardContent className="p-0"><div className="flex items-center justify-between border-b border-border px-5 py-4 dark:border-border-dark"><h2 className="text-sm font-semibold">Questions in this set</h2><Badge variant="outline">{questions.length} total</Badge></div>{questions.length===0?<div className="p-10 text-center text-sm text-muted-foreground">This Question Set is empty. Import or add questions.</div>:questions.map((q,i)=><div key={q.id} className="flex items-start gap-3 border-b border-border p-4 last:border-b-0 dark:border-border-dark"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-xs font-bold text-primary">{i+1}</span><div className="min-w-0 flex-1 cursor-pointer" onClick={()=>navigate(`/teacher/questions/${q.id}/edit`)}><div className="mb-1 flex flex-wrap gap-2"><Badge variant="outline">{QUESTION_TYPE_LABELS[q.type]}</Badge><Badge variant="muted">{DIFFICULTY_LABELS[q.difficulty]}</Badge><span className="text-xs text-muted-foreground">{q.points} pts</span></div><p className="text-sm font-medium">{q.question}</p></div><div className="flex items-center gap-1"><button title="Preview" onClick={()=>navigate(`/teacher/questions/${q.id}/preview`)} className="flex h-9 w-9 items-center justify-center rounded-xl text-muted-foreground hover:bg-muted/40"><Eye size={16}/></button><button title="Duplicate" onClick={async()=>{await duplicateQuestion(q.id);await load()}} className="flex h-9 w-9 items-center justify-center rounded-xl text-muted-foreground hover:bg-muted/40"><Copy size={16}/></button><button title={q.archived?'Restore':'Archive'} onClick={async()=>{await archiveQuestion(q.id,!q.archived);await load()}} className="flex h-9 w-9 items-center justify-center rounded-xl text-muted-foreground hover:bg-muted/40">{q.archived?<RotateCcw size={16}/>:<Archive size={16}/>}</button><button title="Delete" onClick={()=>setConfirmDelete(q.id)} className="flex h-9 w-9 items-center justify-center rounded-xl text-red-500 hover:bg-red-500/10"><Trash2 size={16}/></button></div></div>)}</CardContent></Card>
    <ConfirmDialog open={!!confirmDelete} title="Delete Question" message="This permanently deletes the question. This cannot be undone." confirmLabel="Delete" destructive onConfirm={async()=>{if(confirmDelete){await deleteQuestion(confirmDelete);await load()}setConfirmDelete(null)}} onCancel={()=>setConfirmDelete(null)}/>
  </div>;
}
